### ISSUE TITLE
Eliminar binarios de GitHub

### ISSUE THREAD

**Issue by javiertuya** [IvanCuervo/FireDrone-2425-4#10]
@IvanCuervo @davidgvmoreda @UO276609 Los ficheros de la base de datos son binarios, no deben estar en GitHub, eliminarlos e incluirlos en .gitignore

**Comment by IvanCuervo** [comment]
Buenos días @javiertuya , ¿podrías darnos algún ejemplo de fichero binario?

**Comment by javiertuya** [comment]
@IvanCuervo Me refiero al de la base de datos, el archivo .db es binario
