### ISSUE TITLE
Los puertos asignados no siguen el convenio establecido en el documento de organización

### ISSUE THREAD

**Issue by javiertuya** [IvanCuervo/FireDrone-2425-4#11]
@IvanCuervo @davidgvmoreda @UO276609 Revisar todos los puertos para que sigan el convenio:
*3.1. Todos los proyectos de una misma solución deben utilizar puertos localizados en un rango prefijado para evitar conflictos cuando se ejecuten en un entorno de integración. El rango de puertos es definido en el rango de 5000 como 5Nxx, donde N es el número de equipo, xx es un número de dos dígitos a elegir.*

Cuando esté hecho, devolverme la issue, indicándome el puerto asignado al frontend

**Comment by uo277724** [comment]
Puerto frontend actualizado: 5401

**Comment by javiertuya** [comment]
Actualizado en la configuración para CI
