### ISSUE TITLE
La base de datos no sigue el convenio de nombres

### ISSUE THREAD

**Issue by javiertuya** [IvanCuervo/FireDrone-2425-4#5]
@IvanCuervo @davidgvmoreda @UO276609 Se denomina `Library.db`, tiene que tener el mismo nombre que la solución

**Comment by javiertuya** [comment]
@IvanCuervo Sigue sin cumplir el convenio de nombres, ahora se crea con este nombre: `FireDrone-2425.db`

**Comment by uo277724** [comment]
Se ha modificado el nombre por el de FireDrone-2425-4.db
