### ISSUE TITLE
Múltiples warnings al compilar

### ISSUE THREAD

**Issue by javiertuya** [IvanCuervo/FireDrone-2425-4#8]
@IvanCuervo @davidgvmoreda @UO276609 Hay un excesivo número de warnings al compilar con dotnet build, que pueden causar potenciales problemas a corto plazo. Son todos similares:

`[exec] /home/jenkins/workspace/MII-2425-CPP-4_main/src/Models/Models.cs(10,42): warning CS8618: Non-nullable property 'EstacionesBase' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable. [/home/jenkins/workspace/MII-2425-CPP-4_main/src/Models/Models.csproj]`

**Comment by davidgvmoreda** [comment]
@javiertuya  Buenas tardes, para comprobar de manera más fácil y efectiva este tipo de errores,  ¿nos puedes dar acceso al jenkings?. Nos parece una mejor opción y, aprovechando que comentaste esta posibilidad, creemos que estaría bien de cara a ver todos los logs.

**Comment by javiertuya** [comment]
@davidgvmoreda ok, voy preparando los accesos, pero tener en cuenta que esto no evita que lo antes de hacer el merge.

**Comment by javiertuya** [comment]
@davidgvmoreda Ponme una issue para lo de jenkins, para no mezclar cosas

**Comment by javiertuya** [comment]
@davidgvmoreda He visto que hay una issue, pero NO está asignada
